apiVersion: apps/v1
kind: Deployment
metadata:
  name: samir-controlhe-usuario-api-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: samir-controlhe-usuario-api
  template:
    metadata:
      labels:
        app: samir-controlhe-usuario-api
    spec:
      containers:
      - name: samir-controlhe-usuario-api
        image: moisespompilio/samir_controlhe_usuario:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: samir-controlhe-usuario-db
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: ${DB_USERNAME}
        - name: DB_PASSWORD
          value: ${DB_PASSWORD}
        - name: DB_NAME
          value: ${DB_NAME}
        - name: DB_SYNC
          value: ${DB_SYNC}