version: '3'

services:
  samir_calculadora_api:
    container_name: samir_calculadora_api
    restart: always
    image: moisespompilio/samir_calculadora:1.0.0
    depends_on:
      - samir_calculadora_database
    environment:
      - spring.datasource.url=${SAMIR_CALCULADORA_DB_URL}
      - spring.datasource.username=${SAMIR_CALCULADORA_DB_USERNAME}
      - spring.datasource.password=${SAMIR_CALCULADORA_DB_PASSWORD}
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - ${SAMIR_CALCULADORA}:8888
  samir_calculadora_database:
    container_name: samir_calculadora_database
    image: postgres
    environment:
      POSTGRES_DB: ${SAMIR_CALCULADORA_DB_USERNAME}
      POSTGRES_USER: ${SAMIR_CALCULADORA_DB_USERNAME}
      POSTGRES_PASSWORD: ${SAMIR_CALCULADORA_DB_PASSWORD}
    ports:
    - ${SAMIR_CALCULADORA_DB_HOST}:5432
    volumes:
      - db_data:/var/lib/postgresql/samir_calculadora_database


  visao_api:
    container_name: visao_api
    restart: always
    image: moisespompilio/visao:1.0.0
    environment:
      CMD_Python: python3
    ports:
      - ${VISAO_API}:3004



  samir_controlhe_usuario_api:
    container_name: samir-controlhe-usuario_api
    image: moisespompilio/samir_controle_usuario:1.0.0
    depends_on:
      - samir_controlhe_usuario_database
    ports:
      - ${SAMIR_CONTROLE_USUARIO}:${API}
    environment:
      DB_HOST: samir_controlhe_usuario_database
      DB_PORT: 5432
      DB_USERNAME: ${SAMIR_CONTROLE_USUARIO_DB_USERNAME}
      DB_PASSWORD: ${SAMIR_CONTROLE_USUARIO_DB_PASSWORD}
      DB_NAME: ${SAMIR_CONTROLE_USUARIO_DB_NAME}
  samir_controlhe_usuario_database:
    container_name: samir_controlhe_usuario_database
    image: postgres
    environment:
      POSTGRES_DB: ${SAMIR_CONTROLE_USUARIO_DB_NAME}
      POSTGRES_USER: ${SAMIR_CONTROLE_USUARIO_DB_USERNAME}
      POSTGRES_PASSWORD: ${SAMIR_CONTROLE_USUARIO_DB_PASSWORD}
    ports:
    - ${SAMIR_CONTROLE_USUARIO_DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/samir_controlhe_usuario_database
  
volumes:
  db_data: